### PR TITLE
Ty/record remember

### PR DESCRIPTION
**Pull request by AlephNotation**
Simple replay abiliity

Adds new methods to `page` that allow users to replay actions. We also added two new `BrowserActions` to the mix. The `GoTo` and `Get` actions have been added so we can do programmatic replay for `page.goto` and `page.get`. However we do not expose these new action types to the agent class. Instead they are handled by the `page` object. In the future we may expose `GoTo` to the agent class but that degree of flexibility kind of freaks me out.

### CODE REVIEW

**Comment by AlephNotation** [comment]
Need to make some backend changes before this can go out

**Comment by AlephNotation** [comment]
@matildepark ok we gucci

**Review by matildepark — APPROVED** [review]
Reads normal, example works — but the example is similar to findEmail. I guess I'd just ask if there's a more complex example we can try for something like this. If we have a long route we know works, can we enforce it and replay it and show that it works?

**Comment by AlephNotation** [comment]
Yeah that makes sense. Do you want to merge then update the example or update then merge?

**Comment by matildepark** [comment]
> Yeah that makes sense. Do you want to merge then update the example or update then merge?

I merged dev earlier, above my review.

**Pull request merged**
