### PR TITLE
Ty/better page api

### PR DESCRIPTION
**Pull request by AlephNotation**
changing this around a bit so that the `Page` now has an agent binded to it + optional agent args

### CODE REVIEW

**Comment by matildepark** [comment]
Wait, Browser takes an agent now? What makes it different from AgentBrowser? We could just do it all in the Browser class.

**Review by matildepark — APPROVED** [review]
Docs read nicely in IDE, definitely better to pass agent just once

**Comment by matildepark** [comment]
Page tests all fail though on a timeout.

**Comment by AlephNotation** [comment]
lol finally

**Pull request merged**
