### PR TITLE
bin: rewrite around page instances

### PR DESCRIPTION
**Pull request by matildepark**
Retains current functionality, rewritten around Pages.

Question: do we return `objectiveFailed` ever? The error state appears to exist in `agentBrowser.ts` but not in `page.ts`, and we just bail out without throwing an error. Do I just have to see if we're out of iterations and throw manually?

### CODE REVIEW

**Comment by AlephNotation** [comment]
We can go add that error back in. Would it be helpful?

**Comment by matildepark** [comment]
> We can go add that error back in. Would it be helpful?

I was just understanding if there was a reason (like if it introduced weird edge cases or w/e). Is there a quirk that happens if we specify a step where we return a failed objective browse? Or is it more ergonomic to give no feedback? The last thing we get is the final step it attempts before it returns.

**Comment by AlephNotation** [comment]
Mostly its an artifact of not wanting to make the return type messier. But I think it would provide better dev ergonomics so I will add it back in

**Comment by AlephNotation** [comment]
added the failure case

**Review by AlephNotation — APPROVED** [review]

**Comment by matildepark** [comment]
Test failed on one item because it expects an objective complete type, and the objective failed in the test. Merging into dev.

**Pull request merged**
